{
 "title": "UniFi-Poller: UAP Insights - InfluxDB",
 "description": "UniFi Poller v2.0 Displays detailed information for wireless access points in a UniFi network.",
 "tags": [
  "unifi",
  "uap",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now-5s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "show tag values from \"uap\" with key=\"source\""
   },
   {
    "name": "Site",
    "query": "show tag values from \"uap\" with key=\"site_name\" where source =~ /$Controller$/"
   },
   {
    "name": "AP",
    "label": "UniFi AP:",
    "query": "show tag values from \"uap\" with key=\"name\"  where site_name =~ /$Site$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\n<br>\n<center><b><font size=\"6px\">Unifi UAP</font></b></center>\n"
   }
  },
  {
   "title": "Clients / Channel",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Ch $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE $timeFilter AND ap_name =~ /$AP$/ AND site_name =~ /$Site$/ GROUP BY \"channel\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients / AP Band",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_ap_name $tag_radio_proto",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE ($timeFilter  AND  ap_name =~ /$AP$/ AND site_name =~ /$Site$/) GROUP BY \"radio_proto\", \"ap_name\"",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Client / MAC OUI",
   "type": "grafana-piechart-panel",
   "description": "This shows an OUI breakdown from Unifi's perspective.",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_oui",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE $timeFilter AND ap_name =~ /$AP$/ AND site_name =~ /$Site$/ GROUP BY \"oui\"",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE ($timeFilter AND ap_name =~ /$AP$/ AND site_name =~ /$Site$/)",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Guests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "is_guest" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE ($timeFilter AND ap_name =~ /$AP$/ AND site_name =~ /$Site$/ AND is_guest = \"true\")",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Now", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 } },
  {
   "title": "UAP Details",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "serial" ], "type": "tag" },
      { "params": [ "site_name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Address" ], "type": "alias" }
      ],
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "last_seen" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Last Seen" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "user-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Users" ], "type": "alias" }
      ],
      [
       { "params": [ "guest-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Guests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Networks / UAP",
   "type": "table-old",
   "description": "The counters in this table represent uptime totals and do not change with the time range selector. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "radio" ], "type": "tag" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "site_name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "usage" ], "type": "tag" },
      { "params": [ "essid" ], "type": "tag" },
      { "params": [ "radio_name" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "bssid" ], "type": "tag" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Channel" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bytes Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Clients" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx Packets" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx Packets" ], "type": "alias" }
      ],
      [
       { "params": [ "ccq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/10" ], "type": "math" },
       { "params": [ "CCQ" ], "type": "alias" }
      ],
      [
       { "params": [ "avg_client_signal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Avg Client Sig" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx Drops" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx Drops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$AP$/" }
     ]
    }
   ]
  },
  {
   "title": "UAP CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "UAP Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "query": "SELECT \"mem_used\" FROM \"uap\" WHERE (\"name\" =~ /^$host$/ AND \"site_name\" =~ /^$Site$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "UAP Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "loadavg_1" ], "type": "field" },
       { "params": [ "Avg Load 1" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_5" ], "type": "field" },
       { "params": [ "Avg Load 5" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_15" ], "type": "field" },
       { "params": [ "Avg Load 15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients / UAP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "query": "SELECT last(\"num_sta\") FROM \"uap_radios\" WHERE (\"device_name\" =~ /^$host$/ AND \"radio\" = 'na') AND $timeFilter GROUP BY time($__interval), \"device_name\"",
     "select": [
      [
       { "params": [ "num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$AP$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Traffic / Vendor",
   "type": "graph",
   "description": "Devices TX / RX bytes per second grouped by OUI. RX on negative axis.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_oui $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "oui" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(sum(\"rx_bytes\"), 1s) AS \"Rx\", derivative(sum(\"rx_bytes\"), 1s) AS \"Rx\" FROM \"clients\" WHERE (\"oui\" = 'Htc' AND \"is_wired\" = 'false') AND $timeFilter GROUP BY time(30s), \"oui\" fill(none)",
     "select": [
      [
       { "params": [ "tx_bytes_r" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_bytes_r" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^$AP$/" }
     ]
    }
   ]
  },
  {
   "title": "Users & Guests / UAP band",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name 5GHz $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "user-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Users" ], "type": "alias" }
      ],
      [
       { "params": [ "guest-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Guests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    },
    {
     "alias": "$tag_device_name 2.4GHz $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "guest-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Guests" ], "type": "alias" }
      ],
      [
       { "params": [ "user-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Users" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Client Signal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "dBm", "label": "Client Signal - Average" }
   ],
   "targets": [
    {
     "alias": "$tag_ap_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ap_name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^$AP$/" }
     ]
    }
   ]
  },
  {
   "title": "Average AP RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "dBm", "label": "Rssi" }
   ],
   "targets": [
    {
     "alias": "$tag_ap_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ap_name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "ap_name", "operator": "=~", "value": "/^$AP$/" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "ccq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "2.4 GHz Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "ccq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Channel Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "cu_self_rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_self_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Channel Utilization",
   "type": "graph",
   "description": "Displays 2.4GHz usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "cu_self_rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_self_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Traffic",
   "type": "graph",
   "description": "RX is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Traffic",
   "type": "graph",
   "description": "RX is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$AP$/" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Packets",
   "type": "graph",
   "description": "PPS on the na band. In is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Packets",
   "type": "graph",
   "description": "PPS on the ng band calculated in 30 second buckets. In is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "5GHz Drops/Errors",
   "type": "graph",
   "description": "Visualize packet errors (several types)  per second in the 5GHz band.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "radio" ], "type": "tag" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drops Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drops Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Errors Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Errors Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_crypts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Crypts Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_frags" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Frags Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Retries Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_nwids" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Nwids Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Drops/Errors",
   "type": "graph",
   "description": "In is on the negative axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_vaps",
     "select": [
      [
       { "params": [ "rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drops Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drops Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Errors Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Errors Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_crypts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Crypts Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_frags" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Frags Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Retries Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_nwids" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Nwids Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  }
 ]
}